FROM python
#ARG DEFAULTPORT=1200
#ARG DEFAULTENVIRONMENT="DEV"
#ARG DEFAULTDBURI="mysql://USER:PASSWORD@localhost:3306/sakila"
#ARG DEFAULTUSERNAME="USER"
#ARG DEFAULTPASSWORD="PASSWORD"
#ARG DEFAULTHOST="LOCALHOST"
#ARG DEFAULTSQLPORT=3306
#ARG DEFAULTDBNAME="sakila"
#ARG DEFAULTDBTYPE="mysql"
#ENV ENVIRONMENT=$DEFAULTENVIRONMENT
# ENV SQLALCHEMY_DATABASE_URI="$DEFAULTDBTYPE://$DEFAULTUSERNAME:$DEFAULTPASSWORD@$DEFAULTHOST:$DEFAULTSQLPORT/$DEFAULTDBNAME"

ENV SQLALCHEMY_DATABASE_URI="mysql://USER:PASSWORD@localhost:3306/sakila"
WORKDIR /app
COPY . .
ENV PYTHONPATH "/app/api:/app/api/models:/app/api/routes:/app/api/schemas:${PYTHONPATH}"
COPY requirements.txt .
RUN pip install -r requirements.txt
EXPOSE 5000
CMD python app.py

